### ISSUE TITLE
errors on baqup

### ISSUE THREAD

**Issue by cbertelli** [quip/quip-api#4]
This issue may be inconsistent or due to other problems as the concerned folder was imported from Evernote.
Anyway, I called main like this:
`baqup/main.py --access_token "ABCDEF1GH2abcdd=e123456789f0/g1hilmIJKLMNm2n3oOpqrPQstu45Rvwx6STU78VWX="  --root_folder_id AbCDEFgHHIl --output_directory my_backup`
The first six thread were backed up
`INFO:root:Backing up folder my_quip_folder_0...`
`INFO:root:  Backing up thread Report XANTOS (OOfAAAANU4B)...`
`INFO:root:  Backing up thread Workgroup (HWTAAASVKEL)...`
`INFO:root:  Backing up thread Acronyms (NIaAAAlbMii)...`
`INFO:root:  Backing up thread tricks for ZOTS (KaJAAAMKxPv)...`
`INFO:root:  Backing up thread zots for tricks (dENAAApyH59)...`
`INFO:root:  Backing up thread Z8080 chemin a parcourir (CVAAAAmJ4H6)...`
`INFO:root:  Backing up thread Z8080 pre-verification (VYWAAAVhT5Y)...`
`Traceback (most recent call last):`
`  File "baqup/main.py", line 256, in <module>`
`    main()`
`  File "baqup/main.py", line 68, in main`
`    _run_backup(client, output_directory, args.root_folder_id)`
`  File "baqup/main.py", line 75, in _run_backup`
`    client, output_directory, 0)`
`  File "baqup/main.py", line 118, in _descend_into_folder`
`    _backup_thread(thread, client, folder_output_path, depth + 1)`
`  File "baqup/main.py", line 128, in _backup_thread`
`    tree = client.parse_document_html(thread["html"])`
`  File "/home/myuser/quip/quip-api-master/samples/baqup/quip.py", line 574, in parse_document_html`
`    return xml.etree.cElementTree.fromstring(document_xml.encode("utf-8"))`
`  File "<string>", line 124, in XML`
`cElementTree.ParseError: mismatched tag: line 127, column 346`
Access token, file IDs and document names were changed.
It seems there was a problem in parsing XML. Could it be a wrong utf-8 character or something of the like?

**Comment by caseymrm** [comment]
Thanks for the report- may I have your permission to examine the Z8080 pre-verification (VYWAAAVhT5Y) document to see if I can reproduce?

**Comment by cbertelli** [comment]
Obviously.
I changed every link and name, here is the true report:

INFO:root:Backing up folder hern_0...
INFO:root:  Backing up thread Relazione CARSTOS (OOfAAAANU4B)...
INFO:root:  Backing up thread Workgroup (HWTAAASVKEL)...
INFO:root:  Backing up thread Acronyms (NIaAAAlbMii)...
INFO:root:  Backing up thread dummies for hern (KaJAAAMKxPv)...
INFO:root:  Backing up thread hern for dummies (dENAAApyH59)...
INFO:root:  Backing up thread H2020 cose da fare (CVAAAAmJ4H6)...
INFO:root:  Backing up thread H2020 pre-submission (VYWAAAVhT5Y)...
Traceback (most recent call last):
  File "baqup/main.py", line 256, in <module>
    main()
  File "baqup/main.py", line 68, in main
    _run_backup(client, output_directory, args.root_folder_id)
  File "baqup/main.py", line 75, in _run_backup
    client, output_directory, 0)
  File "baqup/main.py", line 118, in _descend_into_folder
    _backup_thread(thread, client, folder_output_path, depth + 1)
  File "baqup/main.py", line 128, in _backup_thread
    tree = client.parse_document_html(thread["html"])
  File "/Users/carlo/Desktop/HERN/quip-api-master/samples/baqup/quip.py",
line 574, in parse_document_html
    return xml.etree.cElementTree.fromstring(document_xml.encode("utf-8"))
  File "<string>", line 124, in XML
cElementTree.ParseError: mismatched tag: line 127, column 346

ecco il comando:
baqup/main.py --access_token
"TUNPQU1BU2twakk=|1460814688|6/n3cgdOFRlCPk3j7qXugjTYbmf08Mwjx1JDLP30YGM="
--root_folder_id EdFAOAvIIMk --output_directory bkup

There is nothing personal inside, so you can use any other file for any
test.
The name of the specific blocking file is
H2020 pre-sumbission (https://quip.com/s873Ad4XbaTu).

Ciao.
c


On Mon, Apr 20, 2015 at 7:59 PM, Casey Muller <notifications@github.com>
wrote:

> Thanks for the report- may I have your permission to examine the Z8080
> pre-verification (VYWAAAVhT5Y) document to see if I can reproduce?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/quip/quip-api/issues/4#issuecomment-94524961>.
>



-- 
--------------------------------------------------------------------------
Carlo A. Bertelli
   Charta servizi e sistemi per il territorio e la storia ambientale srl
          Dipendenze del palazzo Doria,
          vc. alla Chiesa della Maddalena 9/2 16124      Genova (Italy)
          tel./fax +39(0)10 2475439  +39 0108566195  gsm:+39 393 1590711
   e-mail: bertelli@chartasrl.eu      http://www.chartasrl.eu
--------------------------------------------------------------------------

**Comment by caseymrm** [comment]
The root cause of this appears to be a bug in the evernote importer.

I will file a bug to fix both evernote import and platform export, but for now the issue appears to only be in the link containing "Standard proposal template (administrative forms and structure of technical annex)", so if you delete and recreate that bullet point it may fix it in this case.

So sorry for the trouble!

**Comment by cbertelli** [comment]
How did you spot it? I have several other files and maybe I'll find otrer
blocking errors. I would prefer to fix them myself then passing them to you
to find a fix.
Thank you very much.
c

On Mon, Apr 20, 2015 at 10:41 PM, Casey Muller <notifications@github.com>
wrote:

> The root cause of this appears to be a bug in the evernote importer.
>
> I will file a bug to fix both evernote import and platform export, but for
> now the issue appears to only be in the link containing "Standard proposal
> template (administrative forms and structure of technical annex)", so if
> you delete and recreate that bullet point it may fix it in this case.
>
> So sorry for the trouble!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/quip/quip-api/issues/4#issuecomment-94563059>.
>



-- 
--------------------------------------------------------------------------
Carlo A. Bertelli
   Charta servizi e sistemi per il territorio e la storia ambientale srl
          Dipendenze del palazzo Doria,
          vc. alla Chiesa della Maddalena 9/2 16124      Genova (Italy)
          tel./fax +39(0)10 2475439  +39 0108566195  gsm:+39 393 1590711
   e-mail: bertelli@chartasrl.eu      http://www.chartasrl.eu
--------------------------------------------------------------------------

**Comment by caseymrm** [comment]
I fetched the thread:

    >>> t = client.get_thread("s873Ad4XbaTu")

Parsed the HTML and looked at the error:

    >>> client.parse_document_html(t["html"])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/casey/quip/clients/quip.py", line 619, in parse_document_html
        return xml.etree.cElementTree.fromstring(document_xml.encode("utf-8"))
      File "<string>", line 124, in XML
    cElementTree.ParseError: mismatched tag: line 127, column 346

Confirmed the problem was in that line and looked at its contents:

    >>> client.parse_document_html(t["html"].split("\n")[126])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/casey/quip/clients/quip.py", line 619, in parse_document_html
        return xml.etree.cElementTree.fromstring(document_xml.encode("utf-8"))
      File "<string>", line 124, in XML
    cElementTree.ParseError: mismatched tag: line 1, column 352
    >>> t["html"].split("\n")[126]
    u'<p id=\'VYWACAQTdMx\' class=\'line\'><br/><a href="http://ec.europa.eu/research/participants/data/ref/h2020/call_ptef/pt/h2020-call-pt-ria-ia_en.pdf">Standard proposal template (administrative forms and structure of technical annex)</a><a href="http://ec.europa.eu/research/participants/data/ref/h2020/call_ptef/ef/h2020-call-ef-ria-ia-csa_en.pdf"></p>'

Then finally confirmed the rest of the document was okay:

    >>> client.parse_document_html("\n".join(t["html"].split("\n")[:126] + t["html"].split("\n")[127:]))
    <Element 'html' at 0x106c6d030>

**Comment by cbertelli** [comment]
Thank you.
c
