### ISSUE TITLE
'baqup' consistently fails due to 503: Over Rate Limit

### ISSUE THREAD

**Issue by nrser** [quip/quip-api#44]
```
Traceback (most recent call last):
  File "main.py", line 272, in <module>
    main()
  File "main.py", line 73, in main
    _run_backup(client, output_directory, args.root_folder_id)
  File "main.py", line 83, in _run_backup
    client, output_directory, 0)
  File "main.py", line 120, in _descend_into_folder
    client, folder_output_path, depth + 1)
  File "main.py", line 120, in _descend_into_folder
    client, folder_output_path, depth + 1)
  File "main.py", line 122, in _descend_into_folder
    thread = client.get_thread(child["thread_id"])
  File "/Users/nrser/dev/gh/quip/quip-api/samples/baqup/quip.py", line 247, in get_thread
    return self._fetch_json("threads/" + id)
  File "/Users/nrser/dev/gh/quip/quip-api/samples/baqup/quip.py", line 788, in _fetch_json
    raise QuipError(error.code, message, error)
quip.QuipError: 503: Over Rate Limit
```

I went in and added retry with multiplicative back-off up to about five minutes total... it still can't make it through. Sometimes it gets in a state where it can't even start up, just `503: Over Rate Limit` again and again on every request.

We realized that we have a ton of very important notes in Quip, and really need to back them up. Probably have somewhere between hundreds to low thousands of docs.

What's the deal?

I'm on Python 2.7.14, MacOS 10.12.6 if it makes any difference.

**Comment by ogyet-stockpile** [comment]
Hi @nrser,

Were you able to figure out how to fix that issue? I get the exact same error.  I am looking at the Quip's documentation but I couldn't find any thing about their API limits. :/ 

@willhite, can you help us out with error? BTW, Thanks for publishing this!

**Comment by pio-davidt** [comment]
This rather old tweet says that it's 250 per hour / 15 per minute:
https://twitter.com/QuipSupport/status/527965994761744384

**Comment by jrgoodner** [comment]
@nrser would like to check out your fork...is it published anywhere? Thanks!

**Comment by akido-jared** [comment]
@nrser nvm found your fork! Thx for putting that together!

**Comment by nrser** [comment]
@jrgoodner Yeah there's a link to one of the files in my comment, repo's at:

https://github.com/nrser/quip-api

No promises about code quality; it was a bit of a dirty hack to get it working.

### However ###

It turns out that Quip has *batch* API that let you breeze through the whole thing! IDK if they weren't there back in December or what. Also I've only used them for the JSON data, not sure if they exist for blobs but they make a massive difference over the one request per entity that the Quip python lib at least used to use.

If you need to back up a decent amount or often I would check out hacking those in. Just FYI.
