### ISSUE TITLE
Editing a Slideshow

### ISSUE THREAD

**Issue by pedrocolon93** [quip/quip-api#75]
Hi there,

I am trying to use the API to edit a slideshow, but I get the following:

```
Traceback (most recent call last):
  File "testquip.py", line 17, in <module>
    r = client.edit_document( "GxLtAAShiNmc", "potato", operation=client.APPEND, format="html")
  File "/Users/pedro/Documents/git/quip-api/python/quip.py", line 416, in edit_document
    return self._fetch_json("threads/edit-document", post_data=args)
  File "/Users/pedro/Documents/git/quip-api/python/quip.py", line 808, in _fetch_json
    raise QuipError(error.code, message, error)
quip.QuipError: 400: Invalid or missing slide layout for adding a new slide.
```

Does anyone know what the slide layout is??

**Comment by jesseditson** [comment]
Looks like we have an undocumented required parameter - I've updated the docs internally which should go out in the next week or so. In the meantime, here's a screenshot of the new docs:

![image](https://user-images.githubusercontent.com/370239/85623008-90a08580-b61c-11ea-9139-d42dc9221961.png)

It seems to me like you'll just want to pass `slide_layout=0` unless the only content you're adding is an image tag, in which case you'll use `slide_layout=1`
